vault:
  server:
    ha:
      enabled: true
      replicas: 2
      raft:
        enabled: true
        setNodeId: true

    dataStorage:
      enabled: true
      size: 2Gi
      storageClass: platform-rwo
    
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: vault
            topologyKey: kubernetes.io/hostname

  ui:
    enabled: true

  injector:
    enabled: true

route:
  enabled: true
  hostname: vault.joeriberman.nl
  labels: {}
  oidc:
    enabled: true
    labelKey: oidc
    labelValue: "true"
  parentGateway:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    namespace: envoy-gateway
    sectionName: web-https
  backend:
    group: ''
    kind: Service
    serviceName: vault-ui
    port: 8200
    weight: 1
