argo-cd:
  global:
    domain: argocd.joeriberman.nl

  server:
    service:
      type: LoadBalancer
    
    extraArgs:
      - --insecure

    ingress:
      enabled: false
    
    networkPolicy:
      create: true
      defaultDenyIngress: false

  controller:
    networkPolicy:
      create: true
      defaultDenyIngress: false

  repoServer:
    networkPolicy:
      create: true
      defaultDenyIngress: false

  redis:
    networkPolicy:
      create: true
      defaultDenyIngress: false

  dex:
    networkPolicy:
      create: true
      defaultDenyIngress: false

  notifications:
    enabled: false
    networkPolicy:
      create: true
      defaultDenyIngress: false

  applicationSet:
    enabled: true
    networkPolicy:
      create: true
      defaultDenyIngress: false

  configs:
    params:
      server.insecure: true
    
    cm:
      timeout.reconciliation: 180s
      application.instanceLabelKey: argocd.argoproj.io/instance

